---
# DATA INPUT PARAMETERS
config_id:  # (str) - unique identifier for this configuration, used for voxel space identification
working_dir:  # (str) - working directory for intermediate and output files

# VOLUMETRIC RESAMPLING PARAMETERS
resample_las: True   # (bool) - Do you want to generate a resampled point cloud? (if False, subsequent parameters are ignored)
samps_per_vox: 50  # (int) volumetric resample rate [samples per voxel]
sample_threshold: 0  # (int) noise filter will drop all returns from voxels where total returns <= sample_threshold

# HEMISPHERE RESAMPLING PARAMETERS
resample_hemi: True # (bool) - Do you want to generate synthetic hemispheres? (if False, subsequent parameters are ignored)
batch_dir: ''  # (str) directory for hemisphere batch outputs
pts_in: ""  # (str) path to .csv file with coordinates and elevations at which to calculate hemispheres
            # pts file should include the following header labels: id, easting_m, northing_m, elev_m
img_size: 181  # angular resolution ~ # of samples across 180 deg
max_phi_rad: 90  # (num) maximum zenith angle to sample [deg] (90 deg samples to horizon)
hemi_m_above_ground: 0  # height [m] above ground points (pts_in) at which to generate hemispheres
max_distance: 50  # maximum distance [m] to sample ray (balance computation time with accuracy at distance)
min_distance: 0  # minimum distance [m] to sample ray (default 0, increase to avoid "lens occlusion" within dense voxels)

# HEMISPHERE PROCESSING PARAMETERS
tile_count_1d: 5  # (int) number of square tiles along one side (total # of tiles = tile_count_1d^2)
n_cores: 3  # (int) number of processing cores


# GRID RESAMPLING PARAMETERS
resample_grid: True # (bool) - Do you want to resample at a fixed angle across a grid? (if False, subsequent parameters are ignored)
dem_in:  # raster of 
mask_in: 
phi:  # zenith angle of rays (degrees)
theta:  # azimuth angle of rays (degrees clockwise from north, from above looking down)
max_distance: 50  # maximum distance [m] to sample ray (balance computation time with accuracy at distance)
min_distance: 0  # minimum distance [m] to sample ray (default 0, increase to avoid "lens occlusion" within dense voxels)